# Generated by Django 3.1 on 2020-08-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
        ('Lideres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('programadores', models.CharField(max_length=50)),
                ('computadoras', models.CharField(max_length=50)),
                ('estatus', models.CharField(max_length=50)),
                ('categoria_idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categorias')),
                ('lider_idLider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lideres.lideres')),
            ],
        ),
    ]
